version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "installing something"
  pre_build:
    commands:
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - grep -Fq "hi!" demo.txt
      - echo "hii!" > src/codebuild/result.txt
  post_build:
    commands:
      - echo "we are in the post build phase"
artifacts:
  files:
    - "src/codebuild/*"
  discart-paths: yes
