version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Starting Install Phase"
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discart-paths: yes
