version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Starting Install Phase"
      - cd app
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Removing node_modules"
      - rm -rf node_modules
artifacts:
  files:
    - "**/*"
  base-directory: "app/dist"
  discart-paths: yes
